data_paths:
  train_root_dir: /opt/ml/input/data/train_dataset
  test_root_dir: /opt/ml/input/data/train_dataset
  asset_dir: ./assets
  training_data_file: train_data.csv
  test_data_file: test_data.csv

save_paths:
  root_dir: ./results/
  checkpoints_dir: checkpoint/
  tensorboard_dir: tensorboard/
  yaml_dir: yaml_log/

hyperparameters:
  seed: 327459
  epochs: 120
  clip_grad: 10
  patience: 15
  target: -1

  dataset:
    dataset_args:   # 정답 레이블인 answerCode를 제외한 타겟 feature 리스트
      max_seq_len: 64
      seed: 327459
      target_features:
        - KnowledgeTag
        - assessment_group
        - assessment
        # - question
        - test_interval_sum
        - user_interval_sum
        - user_acc
        - interaction
      shake_range: 8
    gss_args:
      n_splits: 1
      random_state: 327459

  dataloader:
    train_args:
      batch_size: 64
    valid_args:
      batch_size: 64
    test_args:
      batch_size: 64

  model:
    name: DktNewBERT
    args:
      embedding_dim: 32
      hidden_dim: 64
      n_layers: 6
      n_heads: 8

  optimizer:
    name: AdamW
    args:
      lr: 0.0001
      weight_decay: 0.01

  # scheduler:
  #   name: ReduceLROnPlateau
  #   args:
  #     patience: 3
  #     factor: 0.5
  #     mode: max
  #     verbose: True

  scheduler:
    name: CosineAnnealingWarmUpRestarts
    args:
      T_0: 20
      T_mult: 2
      eta_min: 0.000001
      # T_up: 3
      # gamma: 0.66

trainee_name: DBT_Custom
trainee_type: DktNewBertTrainee
